import type { AnalyzedApi, EnrichedRoute } from "../types/api";

export function mockAnalyze(routes: EnrichedRoute[]): AnalyzedApi {
  return {
    info: {
      title: "API Documentation",
      description: "Generated by API Doc AI",
      version: "1.0.0",
    },
    servers: [{ url: "https://your-api.example.com", description: "API server" }],
    endpoints: routes.map((route) => ({
      method: route.method,
      path: route.uri,
      summary: generateSummary(route),
      description: generateDescription(route),
      operationId: `${route.controller.toLowerCase()}_${route.action}`,
      authentication: route.authRequired ? ["bearerAuth"] : [],
      parameters: route.parameters.map((p) => ({
        name: p,
        in: "path" as const,
        required: true,
        description: `The ${p} identifier`,
        schema: { type: "string" },
      })),
      requestBody: ["POST", "PUT", "PATCH"].includes(route.method)
        ? {
            description: `Request body for ${route.action}`,
            required: true,
            content: {
              "application/json": {
                schema: buildValidationSchema(route.validation),
              },
            },
          }
        : null,
      responses: [
        {
          statusCode: 200,
          description: "Successful response",
          content: {
            "application/json": {
              example: buildResponseExample(route),
            },
          },
        },
        ...(route.method === "POST"
          ? [{ statusCode: 201, description: "Created", content: undefined }]
          : []),
        ...(route.method === "DELETE"
          ? [{ statusCode: 204, description: "No content", content: undefined }]
          : []),
        {
          statusCode: 401,
          description: "Unauthorized",
          content: undefined,
        },
        {
          statusCode: 404,
          description: "Not found",
          content: undefined,
        },
        {
          statusCode: 422,
          description: "Validation error",
          content: undefined,
        },
      ],
      tags: [route.controller.replace("Controller", "")],
    })),
  };
}

function generateSummary(route: EnrichedRoute): string {
  const resource = route.controller.replace("Controller", "");
  switch (route.action) {
    case "index":
      return `List ${resource.toLowerCase()}s`;
    case "store":
      return `Create ${resource.toLowerCase()}`;
    case "show":
      return `Get ${resource.toLowerCase()}`;
    case "update":
      return `Update ${resource.toLowerCase()}`;
    case "destroy":
      return `Delete ${resource.toLowerCase()}`;
    default:
      return `${route.action} ${resource.toLowerCase()}`;
  }
}

function generateDescription(route: EnrichedRoute): string {
  const resource = route.controller.replace("Controller", "");
  switch (route.action) {
    case "index":
      return `Retrieve a list of ${resource.toLowerCase()}s.`;
    case "store":
      return `Create a new ${resource.toLowerCase()}.`;
    case "show":
      return `Retrieve a specific ${resource.toLowerCase()} by its ID.`;
    case "update":
      return `Update an existing ${resource.toLowerCase()}.`;
    case "destroy":
      return `Remove a ${resource.toLowerCase()}.`;
    default:
      return `${route.action} operation on ${resource.toLowerCase()}.`;
  }
}

function buildValidationSchema(
  validation: Record<string, string>
): Record<string, unknown> {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  for (const [field, rules] of Object.entries(validation)) {
    const ruleList = rules.split("|");
    const type = ruleList.includes("integer")
      ? "integer"
      : ruleList.includes("numeric")
        ? "number"
        : "string";
    properties[field] = { type };
    if (!ruleList.includes("nullable")) {
      required.push(field);
    }
  }

  return {
    type: "object",
    properties,
    required: required.length > 0 ? required : undefined,
  };
}

function buildResponseExample(route: EnrichedRoute): unknown {
  const resource = route.controller.replace("Controller", "").toLowerCase();
  switch (route.action) {
    case "index":
      return { data: [{ id: 1, name: `Example ${resource}` }] };
    case "show":
      return { data: { id: 1, name: `Example ${resource}` } };
    case "store":
      return {
        data: { id: 1, name: `Example ${resource}`, created_at: new Date().toISOString() },
      };
    case "update":
      return {
        data: { id: 1, name: `Updated ${resource}`, updated_at: new Date().toISOString() },
      };
    default:
      return null;
  }
}
